### ISSUE TITLE
Remove the emoji box as a class name preffix

### ISSUE THREAD

**Issue by ivosabev** [segmentio/ui-box#23]
It seems dangerous practice especially on older browsers. It seems to me that the benefit doesn't offset the risk.

http://adrianroselli.com/2017/10/avoid-emoji-as-class-names.html

**Comment by Rowno** [comment]
That article doesn't mention anything about browser compatibility, only editor compatibility. But since the classes are automatically generated, editor compatibility shouldn't be an issue.

Also this article from 2010 says that unicode class names work in IE6: https://css-tricks.com/unicode-class-names/

**Comment by ivosabev** [comment]
I understand support is very good, but it just seems quite unnecessary.

**Comment by jeroenransijn** [comment]
@Rowno and me disagreed about this before. I don't think the emoji is necessary and might scare people away from using it. It creates high visual noise in the inspector and snapshots test. Just my 2c.

**Comment by stephenmathieson** [comment]
Hi :wave: Segment folks :)

Just want to give my $0.02. I found the emoji class obnoxious awhile back, but didn't personally care enough to discuss it, as I thought it really didn't matter. However, as the linked article explains very well, it does create pretty annoying accessibility problems. This totally changes my viewpoint here, as it _does_ matter. Since there isn't a real benefit (other than being "cute") here, and there are clear drawbacks, I'd like to understand the reasoning for leaving this as-is.

**Comment by mshwery** [comment]
Not sure if this would technically be considered a breaking change (for those who use it in selectors, for instance), but perhaps you could init ui-box with a custom setting for those who wish to change it?

**Comment by jasonbarry** [comment]
May I suggest [Upper Right Shadowed White Square](https://unicode-table.com/en/2752/) (❒) be used instead? It's less jarring IMO since it matches the colors of your devtools.

<img width="895" alt="screen shot 2019-01-26 at 11 59 02 am" src="https://user-images.githubusercontent.com/236451/51792112-cc05fe80-2161-11e9-971e-1970047702fa.png">

**Comment by agonist** [comment]
Hello guys, I'm adding my 2 cents here: https://github.com/segmentio/evergreen/issues/566 
I still don't know if it's coming from the emoji or not but there is clearly something wrong going on my side. I would appreciate any help 🙏

**Comment by tabvn** [comment]
we can add class name like ui-box before, rather than using emoji class name. Thank you and look forward to hear back soon.

**Comment by tabvn** [comment]
i got solution to fix it 

```
npm uninstall --save evergreen-ui

```

**Comment by mshwery** [comment]
This is available in v3.x

**Comment by andrewjrhill** [comment]
For those who stumble on this thread trying to remove the box:

```tsx
import { setClassNamePrefix } from 'ui-box'

const App: React.FC = () => {
    setClassNamePrefix('')

    return (
        <>
            /* Your app code here... */
        </>
    )
}
```

**Comment by mshwery** [comment]
Also if you are on latest there is no 📦 ! :)

**Comment by andrewjrhill** [comment]
>Also if you are on latest there is no 📦 ! :)

Hm. Must be an issue with [Evergreen](https://evergreen.segment.com/) then. I did a fresh install (first time using Evergreen last night) and the 📦 are still in the DOM by default.

**Comment by mshwery** [comment]
Evergreen is manually using the box emoji still because that could be a breaking change for some users. 

It is getting removed in v5 (you can try out the prerelease via `evergreen-ui@next`)

**Comment by andrewjrhill** [comment]
@mshwery - Thanks 👍 appreciate you taking the time to respond.
